//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaracsonyfaRendeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugyfel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ugyfel()
        {
            this.Rendeles = new HashSet<Rendeles>();
        }
    
        public int ugyfel_id { get; set; }
        public string nev { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string irszam { get; set; }
        public string varos { get; set; }
        public string utca { get; set; }
        public string hazszam { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles> Rendeles { get; set; }
    }
}
